// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpixelq_op.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPixelq_op_CfgInitialize(XPixelq_op *InstancePtr, XPixelq_op_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPixelq_op_Start(XPixelq_op *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPixelq_op_IsDone(XPixelq_op *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPixelq_op_IsIdle(XPixelq_op *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPixelq_op_IsReady(XPixelq_op *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPixelq_op_EnableAutoRestart(XPixelq_op *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XPixelq_op_DisableAutoRestart(XPixelq_op *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XPixelq_op_SetRows(XPixelq_op *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XPixelq_op_GetRows(XPixelq_op *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XPixelq_op_SetCols(XPixelq_op *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XPixelq_op_GetCols(XPixelq_op *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XPixelq_op_InterruptGlobalEnable(XPixelq_op *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_GIE, 1);
}

void XPixelq_op_InterruptGlobalDisable(XPixelq_op *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_GIE, 0);
}

void XPixelq_op_InterruptEnable(XPixelq_op *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_IER);
    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XPixelq_op_InterruptDisable(XPixelq_op *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_IER);
    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XPixelq_op_InterruptClear(XPixelq_op *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPixelq_op_WriteReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XPixelq_op_InterruptGetEnabled(XPixelq_op *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_IER);
}

u32 XPixelq_op_InterruptGetStatus(XPixelq_op *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPixelq_op_ReadReg(InstancePtr->Control_bus_BaseAddress, XPIXELQ_OP_CONTROL_BUS_ADDR_ISR);
}

