// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XPIXELQ_OP_H
#define XPIXELQ_OP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xpixelq_op_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XPixelq_op_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XPixelq_op;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XPixelq_op_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XPixelq_op_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XPixelq_op_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XPixelq_op_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XPixelq_op_Initialize(XPixelq_op *InstancePtr, u16 DeviceId);
XPixelq_op_Config* XPixelq_op_LookupConfig(u16 DeviceId);
int XPixelq_op_CfgInitialize(XPixelq_op *InstancePtr, XPixelq_op_Config *ConfigPtr);
#else
int XPixelq_op_Initialize(XPixelq_op *InstancePtr, const char* InstanceName);
int XPixelq_op_Release(XPixelq_op *InstancePtr);
#endif

void XPixelq_op_Start(XPixelq_op *InstancePtr);
u32 XPixelq_op_IsDone(XPixelq_op *InstancePtr);
u32 XPixelq_op_IsIdle(XPixelq_op *InstancePtr);
u32 XPixelq_op_IsReady(XPixelq_op *InstancePtr);
void XPixelq_op_EnableAutoRestart(XPixelq_op *InstancePtr);
void XPixelq_op_DisableAutoRestart(XPixelq_op *InstancePtr);

void XPixelq_op_SetRows(XPixelq_op *InstancePtr, u32 Data);
u32 XPixelq_op_GetRows(XPixelq_op *InstancePtr);
void XPixelq_op_SetCols(XPixelq_op *InstancePtr, u32 Data);
u32 XPixelq_op_GetCols(XPixelq_op *InstancePtr);

void XPixelq_op_InterruptGlobalEnable(XPixelq_op *InstancePtr);
void XPixelq_op_InterruptGlobalDisable(XPixelq_op *InstancePtr);
void XPixelq_op_InterruptEnable(XPixelq_op *InstancePtr, u32 Mask);
void XPixelq_op_InterruptDisable(XPixelq_op *InstancePtr, u32 Mask);
void XPixelq_op_InterruptClear(XPixelq_op *InstancePtr, u32 Mask);
u32 XPixelq_op_InterruptGetEnabled(XPixelq_op *InstancePtr);
u32 XPixelq_op_InterruptGetStatus(XPixelq_op *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
