// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpixelq_op.h"

extern XPixelq_op_Config XPixelq_op_ConfigTable[];

XPixelq_op_Config *XPixelq_op_LookupConfig(u16 DeviceId) {
	XPixelq_op_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPIXELQ_OP_NUM_INSTANCES; Index++) {
		if (XPixelq_op_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPixelq_op_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPixelq_op_Initialize(XPixelq_op *InstancePtr, u16 DeviceId) {
	XPixelq_op_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPixelq_op_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPixelq_op_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

