webtalk_init -webtalk_dir C:\\AVNET_ZED_HDMI\\example.hls\\example.hls.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "??? ?? 24 23:45:36 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210890940_1777499929_210580192_702" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6b3m2kr3p1s7nrgje4pfov1p27" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_45" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "45" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2295 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1429890251546" -context "sdk\\\\bsp/1429890251546"
webtalk_add_data -client sdk -key hwid -value "1429889712487" -context "sdk\\\\bsp/1429890251546"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1429890251546"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1429890251546"
webtalk_transmit -clientid 2274688994 -regid "210890940_1777499929_210580192_702" -xml C:\\AVNET_ZED_HDMI\\example.hls\\example.hls.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\AVNET_ZED_HDMI\\example.hls\\example.hls.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\AVNET_ZED_HDMI\\example.hls\\example.hls.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
